### ISSUE TITLE
small tweak for plugins shown in webview

### ISSUE THREAD

**Issue by xdamman** [citizenwallet/app#156]
Instead of sliding the webview from the right, make it slide from the bottom, it takes more time but that's good because it takes time to load the plugin.

Also, instead of the left arrow top left to close (which is very annoying as it forces the plugin to add a lot of top padding), replace that with a cross top right. Easier to keep that space empty.

https://github.com/user-attachments/assets/319e8e4b-ded6-4f63-a5ec-112ba7b8a27a

**Comment by xdamman** [comment]
Can we rollback this?
It's a regression. The point is not to recreate a mini browser experience. We just need a way to close the view.
![image](https://github.com/user-attachments/assets/c9a178a7-b7b0-4666-8f26-b8f5af83e0a2)

**Comment by kevtechi** [comment]
On there being padding: The padding is in the website, can be removed now 
On navigation controls: The point here was to also to provide navigation controls because websites are not designed like apps and don't always have those. Especially in this market place plugin, it was difficult for me to go back.
